src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FilmRepository::class)
 */
class Film
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $resume;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $duree;

    /**
     * @ORM\Column(type="integer")
     */
    private $annee_sortie;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\ManyToOne(targetEntity=Realisateur::class, inversedBy="films")
     * @ORM\JoinColumn(nullable=false)
     */
    private $realisateur_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    public function getDuree(): ?string
    {
        return $this->duree;
    }

    public function setDuree(string $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getAnneeSortie(): ?int
    {
        return $this->annee_sortie;
    }

    public function setAnneeSortie(int $annee_sortie): self
    {
        $this->annee_sortie = $annee_sortie;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getRealisateurId(): ?Realisateur
    {
        return $this->realisateur_id;
    }

    public function setRealisateurId(?Realisateur $realisateur_id): self
    {
        $this->realisateur_id = $realisateur_id;

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Film;
use App\Entity\Realisateur;
use App\Form\FilmType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class DashboardController extends AbstractController
{

    /**
     * @Route("/dashboard", name="show_dashboard", methods={"GET"})
     */
    public function showDashboard(EntityManagerInterface $entityManager)
    {
        $films = $entityManager->getRepository(Film::class)->findBy([]);
        $realisateurs = $entityManager->getRepository(Realisateur::class)->findBy([]);

        return $this->render('dashboard/tableau_de_bord.html.twig', [
            "films" => $films,
            "realisateurs" => $realisateurs
        ]);
    }

    /**
     * @Route("/dashboard/create/film", name="create_film", methods={"GET|POST"})
     * @param Request $request
     * @return Response
     */
    public function createFilm(Request $request, SluggerInterface $slugger, EntityManagerInterface $entityManager): Response
    {
        # Nouvelle instance de la classe
        $film = new Film();

        # Matérialisation du formulaire déclaré dans FilmType.php
        $form = $this->createForm(FilmType::class, $film);

        # handleRequest() sert à récupérer les données du formulaire
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            //$film->setAuthor($this->getUser());

            # Récupération des données du formulaire
            $film = $form->getData();

            # Création du conteneur et insertion en base de données grâce à Doctrine et l'outil entityManager.
            $entityManager->persist($film);

            # On vide l'entity manager des données précédement contenues.
            $entityManager->flush();

            $this->addFlash('success', 'Vous avez créé un nouuveau film !');

            # Redirection sur la page d'accueil
            return $this->redirectToRoute('show_dashboard');
        }

        return $this->render('dashboard/form_tableau_de_bord.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/dashboard/form_tableau_de_bord.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container">
		<div class="row my-4 d-flex align-middle justify-content-center">
			<div class="col-12">
				{% if article is defined %}
					<h3 class="text-center">Modification d'un film</h3>
				{% else %}
					<h3 class="text-center">Création d'un film</h3>
				{% endif %}

			</div>
		</div>
		<div class="row my-4 d-flex align-middle justify-content-center">
			<div class="col-8 mx-auto">
				{{ form_start(form, { 'attr': { novalidate: 'novalidate' }, 'method': 'POST' } ) }}

				{{ form_row(form.titre) }}
				{{ form_row(form.resume) }}
				{{ form_row(form.duree) }}
				{{ form_row(form.annee_sortie) }}
				{{ form_row(form.prix) }}
                {{ form_row(form.realisateurId) }}
				{% if article is defined %}
					{{ form_row(form.submit, { 'label': 'Modifier le film' }) }}
				{% else %}
					{{ form_row(form.submit, { 'label': 'Créer le film' }) }}
				{% endif %}
				{{ form_end(form) }}
			</div>
		</div>
	</div>
{% endblock %}

templates/dashboard/tableau_de_bord.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<div class="container-fluid">
		<div class="row">
			<div class="col-md-8">
				<h2 class="text-center mt-5 mb-3">Tableau de board</h2>
			</div>
			<div class="col-md-4">
				<a href="{{ path('create_film') }}" class="btn btn-info mt-5 mb-3">
					<i class="fa fa-star"></i>
					Nouveau film
				</a>
			</div>
			<div class="col-md-7">
				<h2 class="text-center my-5">Films</h2>
				<div class="row mx-0">
					<table class="table col-12">
						<thead>
							<tr>
								<th class="text-center" scope="col">ID</th>
								<th class="text-center" scope="col">Titre</th>
								<th class="text-center" scope="col">Resume</th>
								<th class="text-center" scope="col">Durée</th>
								<th class="text-center" scope="col">Année sortie</th>
								<th class="text-center" scope="col">Prix en €</th>
								<th class="text-center" scope="col">Réalisateur</th>
								<th class="text-center" scope="col">Action</th>
							</tr>
						</thead>
						<tbody>
							{% for film in films %}
								<tr>
									<td class="text-center">
										{{ film.id }}
									</td>
									<td class="text-center">
										{{ film.titre }}
									</td>
									<td class="text-center">
										{{ film.resume }}
									</td>
									<td class="text-center">
										{{ film.duree }}
									</td>
									<td class="text-center">
										{{ film.anneeSortie }}
									</td>
									<td class="text-center">
										{{ film.prix }}
									</td>
									<td class="text-center">
										Mr/Mme.
										{{ film.realisateurId.nom }}
									</td>
									<td class="text-center">
										<a href="#" class="btn btn-primary">
											<i class="fa fa-edit"></i>
										</a>
										&nbsp;
										<a href="#" class="btn btn-danger">
											<i class="fa fa-trash"></i>
										</a>
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
			<div class="col-md-5">
				<h2 class="text-center my-5">Réalisateur</h2>
				<div class="row mx-0">
					<table class="table col-12">
						<thead>
							<tr>
								<th class="text-center" scope="col">ID</th>
								<th class="text-center" scope="col">Prenom</th>
								<th class="text-center" scope="col">Nom</th>
								<th class="text-center" scope="col">Pays</th>
								<th class="text-center" scope="col">Action</th>
							</tr>
						</thead>
						<tbody>
							{% for realisateur in realisateurs %}
								<tr>
									<td class="text-center">
										{{ realisateur.id }}
									</td>
									<td class="text-center">
										{{ realisateur.prenom }}
									</td>
									<td class="text-center">
										{{ realisateur.nom }}
									</td>
									<td class="text-center">
										{{ realisateur.pays }}
									</td>
									<td class="text-center">
										<a href="#" class="btn btn-primary">
											<i class="fa fa-edit"></i>
										</a>
										&nbsp;
										<a href="#" class="btn btn-danger">
											<i class="fa fa-trash"></i>
										</a>
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

{% endblock %}